version: '3.7'

services:

    monolith-main:
      container_name: monolith
      build:
        context: .
        dockerfile: Dockerfile
      command: java -jar /app.jar --module.enabled=false --server.port=8181
      ports:
        - "8081:8081"
      deploy:
        resources:
          limits:
            cpus: '1'
            memory: 1G

  module-main:
    container_name: module_main
    build:
      context: .
      dockerfile: Dockerfile
    command: java -jar /app.jar
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    depends_on:
      - module-calculation


  module-calculation:
    container_name: module_product_1
    build:
      context: .
      dockerfile: Dockerfile
    command: java -jar /app.jar --module.name=some-module --server.port=8082
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    ports:
      - "8082:8082"

  module-calculation-2:
    container_name: module_product_2
    build:
      context: .
      dockerfile: Dockerfile
    command: java -jar /app.jar --module.name=some-module --server.port=8083
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    ports:
      - "8083:8083"


  module-calculation-3:
    container_name: module_product_3
    build:
      context: .
      dockerfile: Dockerfile
    command: java -jar /app.jar --module.name=some-module --server.port=8084
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    ports:
      - "8084:8084"

  #  cadvisor:
  #    image: google/cadvisor:latest
  #    ports:
  #      - "9080:8080"
  #    volumes:
  #      - ./cadvisor:/rootfs
  #      - ./cadvisor/var/run:/var/run
  #      - ./cadvisor/sys:/sys
  #      - ./cadvisor/var/lib/docker/:/var/lib/docker
  #      - ./cadvisor/dev/disk/:/dev/disk

  grafana:
    container_name: grafana
    build: './config/grafana'
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
      #      - ./my-temp:/etc
      - ./config/custom.ini:/etc/grafana/grafana.ini
    #      - ./my-temp:/etc/grafana/

    #    environment:
    #      GF_SECURITY_ADMIN_USER: user
    #      GF_SECURITY_ADMIN_PASSWORD: 1234
    #      - GF_SECURITY_ADMIN_USER=admin1
    #      - GF_SECURITY_ADMIN_PASSWORD=admin1
    #      - GF_Security_AdminUser=admin1
    #      - GF_Security_AdminPassword=admin1
    #      - GF_Dashboards_MinRefreshInterval=1s

    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus

#  monolith-main:
#    container_name: monolith
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: java -jar /app.jar --module.enabled=false --server.port=8181
#    ports:
#      - "8181:8181"
#    deploy:
#      resources:
#        limits:
#          cpus: '1'
#          memory: 1G



networks:
  monitoring:

volumes:
  prometheus:
